// Mocks generated by Mockito 5.0.15 from annotations
// in ayah_search/test/features/ayah_search/data/repositories/ayah_search_reposiotory_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:ayah_search/core/network/network_info.dart' as _i6;
import 'package:ayah_search/features/ayah_search/data/datasources/ayah_search_local_data_source.dart'
    as _i5;
import 'package:ayah_search/features/ayah_search/data/datasources/ayah_search_remote_data_source.dart'
    as _i3;
import 'package:ayah_search/features/ayah_search/data/models/ayah_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeAyahModel_0 extends _i1.Fake implements _i2.AyahModel {}

/// A class which mocks [AyahSearchRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAyahSearchRemoteDataSource extends _i1.Mock
    implements _i3.AyahSearchRemoteDataSource {
  MockAyahSearchRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AyahModel> getArabicAyah(String? query) =>
      (super.noSuchMethod(Invocation.method(#getArabicAyah, [query]),
              returnValue: Future<_i2.AyahModel>.value(_FakeAyahModel_0()))
          as _i4.Future<_i2.AyahModel>);
  @override
  _i4.Future<_i2.AyahModel> getTranslationAyah(
          {String? query, String? identifier}) =>
      (super.noSuchMethod(
              Invocation.method(#getTranslationAyah, [],
                  {#query: query, #identifier: identifier}),
              returnValue: Future<_i2.AyahModel>.value(_FakeAyahModel_0()))
          as _i4.Future<_i2.AyahModel>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [AyahSearchLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAyahSearchLocalDataSource extends _i1.Mock
    implements _i5.AyahSearchLocalDataSource {
  MockAyahSearchLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AyahModel> getArabicAyah(String? query) =>
      (super.noSuchMethod(Invocation.method(#getArabicAyah, [query]),
              returnValue: Future<_i2.AyahModel>.value(_FakeAyahModel_0()))
          as _i4.Future<_i2.AyahModel>);
  @override
  _i4.Future<_i2.AyahModel> getTranslationAyah(
          {String? query, String? identifier}) =>
      (super.noSuchMethod(
              Invocation.method(#getTranslationAyah, [],
                  {#query: query, #identifier: identifier}),
              returnValue: Future<_i2.AyahModel>.value(_FakeAyahModel_0()))
          as _i4.Future<_i2.AyahModel>);
  @override
  _i4.Future<void> cacheAyah(_i2.AyahModel? ayahModel) =>
      (super.noSuchMethod(Invocation.method(#cacheAyah, [ayahModel]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get hasConnection =>
      (super.noSuchMethod(Invocation.getter(#hasConnection),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  String toString() => super.toString();
}
