// Mocks generated by Mockito 5.0.15 from annotations
// in ayah_search/test/features/ayah_search/presentation/controller/ayah_search_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:ayah_search/core/error/failures.dart' as _i6;
import 'package:ayah_search/features/ayah_search/domain/entities/ayah.dart'
    as _i7;
import 'package:ayah_search/features/ayah_search/domain/repositories/ayah_search_repository.dart'
    as _i2;
import 'package:ayah_search/features/ayah_search/domain/usecases/get_arabic_ayah.dart'
    as _i4;
import 'package:ayah_search/features/ayah_search/domain/usecases/get_translation_ayah.dart'
    as _i8;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeAyahSearchRepository_0 extends _i1.Fake
    implements _i2.AyahSearchRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetArabicAyah].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetArabicAyah extends _i1.Mock implements _i4.GetArabicAyah {
  MockGetArabicAyah() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AyahSearchRepository get repository => (super.noSuchMethod(
      Invocation.getter(#repository),
      returnValue: _FakeAyahSearchRepository_0()) as _i2.AyahSearchRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Ayah>> call(String? query) =>
      (super.noSuchMethod(Invocation.method(#call, [query]),
              returnValue: Future<_i3.Either<_i6.Failure, _i7.Ayah>>.value(
                  _FakeEither_1<_i6.Failure, _i7.Ayah>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Ayah>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetTranslationAyah].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTranslationAyah extends _i1.Mock
    implements _i8.GetTranslationAyah {
  MockGetTranslationAyah() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AyahSearchRepository get repository => (super.noSuchMethod(
      Invocation.getter(#repository),
      returnValue: _FakeAyahSearchRepository_0()) as _i2.AyahSearchRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Ayah>> call(_i8.Params? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, _i7.Ayah>>.value(
                  _FakeEither_1<_i6.Failure, _i7.Ayah>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Ayah>>);
  @override
  String toString() => super.toString();
}
